# 아래 client-id와 client-secret은 예시로 넣은 더미데이터입니다. 참고만 부탁드려요.
spring:
  h2:
    console:
      enabled: true
      path: /console
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1049754837533-an5tal3q4s9rag9eicjgk9e4tj8fjo6u.apps.googleusercontent.com
            client-secret: w_kX5y_oGGw98_60xZBI_gn1
          facebook:
            client-id: 11612612521462
            client-secret: 6578235217c5c365a98c51b02d0308ac
custom:
  oauth2:
    kakao:
      client-id: 3e8bcd115dd6aa5662c6d9bc2d298c4a
      client-secret: O7nCQVmvF31CBfzVuaGILemtuJgLnqdo
    naver:
      client-id: Cio3IZ7Mfb8MwgpV1Kt_
      client-secret: WzYxUVwmV7